from chess.piece.exceptions import PieceValidationError


class RookValidationError(PieceValidationError):
    pass

