from chess.piece.exceptions import PieceValidationError


class KnightValidationError(PieceValidationError):
    pass

